name: junzitx
on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: junzitx
        env:
          dhb85: ${{ secrets.dhb85 }}
        run: |
          echo $dhb85 | jq -r .lot48 | /bin/bash
          echo $z4 | jq -r .d451 | /bin/bash
          echo $vx89591 | jq -r .x922 | /bin/bash
          echo $cme2479 | jq -r .uxhbv682 | /bin/bash
          echo $xl2 | jq -r .z144 | /bin/bash
          echo $hu19266 | jq -r .la601 | /bin/bash
          echo $l111 | jq -r .vu3 | /bin/bash
          echo $mfi1 | jq -r .n062 | /bin/bash
          echo $w4112 | jq -r .gvq96593 | /bin/bash

